sudo: false

language: erlang

before_install:
  - pip install --user cpp-coveralls coveralls-merge

install:
  - ./configure --enable-gcov
  - rebar3 get-deps

script: rebar3 compile xref && rebar3 eunit

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json

otp_release:
  - 17.1
  - 17.5
  - 18.1
  - 19.3
  - 22.3
  - 23.0
