language: erlang

os: linux

dist: xenial

before_install:
  - pip install --user cpp-coveralls

install:
  - ./configure --enable-gcov
  - rebar get-deps

script: rebar compile xref && rebar skip_deps=true eunit

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - pip install --user coveralls-merge
  - coveralls-merge c.json erlang.json

otp_release:
  - 17.1
  - 17.5
  - 18.1
  - 19.3
  - 22.3
  - 23.0
